from distutils.core import setup

setup(
    name='PCK_SBD',
    version='0.0.1',
    packages=['env.lib.python3.5.distutils', 'env.lib.python3.5.encodings', 'env.lib.python3.5.importlib',
              'env.lib.python3.5.collections', 'env.lib.python3.5.site-packages.pip',
              'env.lib.python3.5.site-packages.pip._vendor', 'env.lib.python3.5.site-packages.pip._vendor.idna',
              'env.lib.python3.5.site-packages.pip._vendor.pep517',
              'env.lib.python3.5.site-packages.pip._vendor.pytoml',
              'env.lib.python3.5.site-packages.pip._vendor.certifi',
              'env.lib.python3.5.site-packages.pip._vendor.chardet',
              'env.lib.python3.5.site-packages.pip._vendor.chardet.cli',
              'env.lib.python3.5.site-packages.pip._vendor.distlib',
              'env.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.5.site-packages.pip._vendor.msgpack',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3.util',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3.contrib',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3.packages',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3.packages.backports',
              'env.lib.python3.5.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.5.site-packages.pip._vendor.colorama',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.5.site-packages.pip._vendor.lockfile',
              'env.lib.python3.5.site-packages.pip._vendor.progress',
              'env.lib.python3.5.site-packages.pip._vendor.requests',
              'env.lib.python3.5.site-packages.pip._vendor.packaging',
              'env.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.5.site-packages.pip._vendor.webencodings',
              'env.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.5.site-packages.pip._internal', 'env.lib.python3.5.site-packages.pip._internal.cli',
              'env.lib.python3.5.site-packages.pip._internal.req', 'env.lib.python3.5.site-packages.pip._internal.vcs',
              'env.lib.python3.5.site-packages.pip._internal.utils',
              'env.lib.python3.5.site-packages.pip._internal.models',
              'env.lib.python3.5.site-packages.pip._internal.commands',
              'env.lib.python3.5.site-packages.pip._internal.operations', 'env.lib.python3.5.site-packages.pytz',
              'env.lib.python3.5.site-packages.wheel', 'env.lib.python3.5.site-packages.wheel.cli',
              'env.lib.python3.5.site-packages.django', 'env.lib.python3.5.site-packages.django.db',
              'env.lib.python3.5.site-packages.django.db.models',
              'env.lib.python3.5.site-packages.django.db.models.sql',
              'env.lib.python3.5.site-packages.django.db.models.fields',
              'env.lib.python3.5.site-packages.django.db.models.functions',
              'env.lib.python3.5.site-packages.django.db.backends',
              'env.lib.python3.5.site-packages.django.db.backends.base',
              'env.lib.python3.5.site-packages.django.db.backends.dummy',
              'env.lib.python3.5.site-packages.django.db.backends.mysql',
              'env.lib.python3.5.site-packages.django.db.backends.oracle',
              'env.lib.python3.5.site-packages.django.db.backends.sqlite3',
              'env.lib.python3.5.site-packages.django.db.backends.postgresql',
              'env.lib.python3.5.site-packages.django.db.backends.postgresql_psycopg2',
              'env.lib.python3.5.site-packages.django.db.migrations',
              'env.lib.python3.5.site-packages.django.db.migrations.operations',
              'env.lib.python3.5.site-packages.django.apps', 'env.lib.python3.5.site-packages.django.conf',
              'env.lib.python3.5.site-packages.django.conf.urls', 'env.lib.python3.5.site-packages.django.conf.locale',
              'env.lib.python3.5.site-packages.django.conf.locale.ar',
              'env.lib.python3.5.site-packages.django.conf.locale.az',
              'env.lib.python3.5.site-packages.django.conf.locale.bg',
              'env.lib.python3.5.site-packages.django.conf.locale.bn',
              'env.lib.python3.5.site-packages.django.conf.locale.bs',
              'env.lib.python3.5.site-packages.django.conf.locale.ca',
              'env.lib.python3.5.site-packages.django.conf.locale.cs',
              'env.lib.python3.5.site-packages.django.conf.locale.cy',
              'env.lib.python3.5.site-packages.django.conf.locale.da',
              'env.lib.python3.5.site-packages.django.conf.locale.de',
              'env.lib.python3.5.site-packages.django.conf.locale.el',
              'env.lib.python3.5.site-packages.django.conf.locale.en',
              'env.lib.python3.5.site-packages.django.conf.locale.eo',
              'env.lib.python3.5.site-packages.django.conf.locale.es',
              'env.lib.python3.5.site-packages.django.conf.locale.et',
              'env.lib.python3.5.site-packages.django.conf.locale.eu',
              'env.lib.python3.5.site-packages.django.conf.locale.fa',
              'env.lib.python3.5.site-packages.django.conf.locale.fi',
              'env.lib.python3.5.site-packages.django.conf.locale.fr',
              'env.lib.python3.5.site-packages.django.conf.locale.fy',
              'env.lib.python3.5.site-packages.django.conf.locale.ga',
              'env.lib.python3.5.site-packages.django.conf.locale.gd',
              'env.lib.python3.5.site-packages.django.conf.locale.gl',
              'env.lib.python3.5.site-packages.django.conf.locale.he',
              'env.lib.python3.5.site-packages.django.conf.locale.hi',
              'env.lib.python3.5.site-packages.django.conf.locale.hr',
              'env.lib.python3.5.site-packages.django.conf.locale.hu',
              'env.lib.python3.5.site-packages.django.conf.locale.id',
              'env.lib.python3.5.site-packages.django.conf.locale.is',
              'env.lib.python3.5.site-packages.django.conf.locale.it',
              'env.lib.python3.5.site-packages.django.conf.locale.ja',
              'env.lib.python3.5.site-packages.django.conf.locale.ka',
              'env.lib.python3.5.site-packages.django.conf.locale.km',
              'env.lib.python3.5.site-packages.django.conf.locale.kn',
              'env.lib.python3.5.site-packages.django.conf.locale.ko',
              'env.lib.python3.5.site-packages.django.conf.locale.lt',
              'env.lib.python3.5.site-packages.django.conf.locale.lv',
              'env.lib.python3.5.site-packages.django.conf.locale.mk',
              'env.lib.python3.5.site-packages.django.conf.locale.ml',
              'env.lib.python3.5.site-packages.django.conf.locale.mn',
              'env.lib.python3.5.site-packages.django.conf.locale.nb',
              'env.lib.python3.5.site-packages.django.conf.locale.nl',
              'env.lib.python3.5.site-packages.django.conf.locale.nn',
              'env.lib.python3.5.site-packages.django.conf.locale.pl',
              'env.lib.python3.5.site-packages.django.conf.locale.pt',
              'env.lib.python3.5.site-packages.django.conf.locale.ro',
              'env.lib.python3.5.site-packages.django.conf.locale.ru',
              'env.lib.python3.5.site-packages.django.conf.locale.sk',
              'env.lib.python3.5.site-packages.django.conf.locale.sl',
              'env.lib.python3.5.site-packages.django.conf.locale.sq',
              'env.lib.python3.5.site-packages.django.conf.locale.sr',
              'env.lib.python3.5.site-packages.django.conf.locale.sv',
              'env.lib.python3.5.site-packages.django.conf.locale.ta',
              'env.lib.python3.5.site-packages.django.conf.locale.te',
              'env.lib.python3.5.site-packages.django.conf.locale.th',
              'env.lib.python3.5.site-packages.django.conf.locale.tr',
              'env.lib.python3.5.site-packages.django.conf.locale.uk',
              'env.lib.python3.5.site-packages.django.conf.locale.vi',
              'env.lib.python3.5.site-packages.django.conf.locale.de_CH',
              'env.lib.python3.5.site-packages.django.conf.locale.en_AU',
              'env.lib.python3.5.site-packages.django.conf.locale.en_GB',
              'env.lib.python3.5.site-packages.django.conf.locale.es_AR',
              'env.lib.python3.5.site-packages.django.conf.locale.es_CO',
              'env.lib.python3.5.site-packages.django.conf.locale.es_MX',
              'env.lib.python3.5.site-packages.django.conf.locale.es_NI',
              'env.lib.python3.5.site-packages.django.conf.locale.es_PR',
              'env.lib.python3.5.site-packages.django.conf.locale.pt_BR',
              'env.lib.python3.5.site-packages.django.conf.locale.sr_Latn',
              'env.lib.python3.5.site-packages.django.conf.locale.zh_Hans',
              'env.lib.python3.5.site-packages.django.conf.locale.zh_Hant',
              'env.lib.python3.5.site-packages.django.core', 'env.lib.python3.5.site-packages.django.core.mail',
              'env.lib.python3.5.site-packages.django.core.mail.backends',
              'env.lib.python3.5.site-packages.django.core.cache',
              'env.lib.python3.5.site-packages.django.core.cache.backends',
              'env.lib.python3.5.site-packages.django.core.files', 'env.lib.python3.5.site-packages.django.core.checks',
              'env.lib.python3.5.site-packages.django.core.checks.security',
              'env.lib.python3.5.site-packages.django.core.checks.compatibility',
              'env.lib.python3.5.site-packages.django.core.servers',
              'env.lib.python3.5.site-packages.django.core.handlers',
              'env.lib.python3.5.site-packages.django.core.management',
              'env.lib.python3.5.site-packages.django.core.management.commands',
              'env.lib.python3.5.site-packages.django.core.serializers', 'env.lib.python3.5.site-packages.django.http',
              'env.lib.python3.5.site-packages.django.test', 'env.lib.python3.5.site-packages.django.urls',
              'env.lib.python3.5.site-packages.django.forms', 'env.lib.python3.5.site-packages.django.forms.extras',
              'env.lib.python3.5.site-packages.django.utils',
              'env.lib.python3.5.site-packages.django.utils.translation',
              'env.lib.python3.5.site-packages.django.views', 'env.lib.python3.5.site-packages.django.views.generic',
              'env.lib.python3.5.site-packages.django.views.decorators',
              'env.lib.python3.5.site-packages.django.contrib', 'env.lib.python3.5.site-packages.django.contrib.gis',
              'env.lib.python3.5.site-packages.django.contrib.gis.db',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.models',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.models.sql',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.backends',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.backends.base',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.backends.mysql',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.backends.oracle',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.backends.postgis',
              'env.lib.python3.5.site-packages.django.contrib.gis.db.backends.spatialite',
              'env.lib.python3.5.site-packages.django.contrib.gis.gdal',
              'env.lib.python3.5.site-packages.django.contrib.gis.gdal.raster',
              'env.lib.python3.5.site-packages.django.contrib.gis.gdal.prototypes',
              'env.lib.python3.5.site-packages.django.contrib.gis.geos',
              'env.lib.python3.5.site-packages.django.contrib.gis.geos.prototypes',
              'env.lib.python3.5.site-packages.django.contrib.gis.admin',
              'env.lib.python3.5.site-packages.django.contrib.gis.forms',
              'env.lib.python3.5.site-packages.django.contrib.gis.geoip',
              'env.lib.python3.5.site-packages.django.contrib.gis.utils',
              'env.lib.python3.5.site-packages.django.contrib.gis.geoip2',
              'env.lib.python3.5.site-packages.django.contrib.gis.geometry',
              'env.lib.python3.5.site-packages.django.contrib.gis.geometry.backend',
              'env.lib.python3.5.site-packages.django.contrib.gis.sitemaps',
              'env.lib.python3.5.site-packages.django.contrib.gis.management',
              'env.lib.python3.5.site-packages.django.contrib.gis.management.commands',
              'env.lib.python3.5.site-packages.django.contrib.gis.serializers',
              'env.lib.python3.5.site-packages.django.contrib.auth',
              'env.lib.python3.5.site-packages.django.contrib.auth.tests',
              'env.lib.python3.5.site-packages.django.contrib.auth.handlers',
              'env.lib.python3.5.site-packages.django.contrib.auth.management',
              'env.lib.python3.5.site-packages.django.contrib.auth.management.commands',
              'env.lib.python3.5.site-packages.django.contrib.auth.migrations',
              'env.lib.python3.5.site-packages.django.contrib.admin',
              'env.lib.python3.5.site-packages.django.contrib.admin.views',
              'env.lib.python3.5.site-packages.django.contrib.admin.migrations',
              'env.lib.python3.5.site-packages.django.contrib.admin.templatetags',
              'env.lib.python3.5.site-packages.django.contrib.sites',
              'env.lib.python3.5.site-packages.django.contrib.sites.migrations',
              'env.lib.python3.5.site-packages.django.contrib.humanize',
              'env.lib.python3.5.site-packages.django.contrib.humanize.templatetags',
              'env.lib.python3.5.site-packages.django.contrib.messages',
              'env.lib.python3.5.site-packages.django.contrib.messages.storage',
              'env.lib.python3.5.site-packages.django.contrib.postgres',
              'env.lib.python3.5.site-packages.django.contrib.postgres.forms',
              'env.lib.python3.5.site-packages.django.contrib.postgres.fields',
              'env.lib.python3.5.site-packages.django.contrib.postgres.aggregates',
              'env.lib.python3.5.site-packages.django.contrib.sessions',
              'env.lib.python3.5.site-packages.django.contrib.sessions.backends',
              'env.lib.python3.5.site-packages.django.contrib.sessions.management',
              'env.lib.python3.5.site-packages.django.contrib.sessions.management.commands',
              'env.lib.python3.5.site-packages.django.contrib.sessions.migrations',
              'env.lib.python3.5.site-packages.django.contrib.sitemaps',
              'env.lib.python3.5.site-packages.django.contrib.sitemaps.management',
              'env.lib.python3.5.site-packages.django.contrib.sitemaps.management.commands',
              'env.lib.python3.5.site-packages.django.contrib.admindocs',
              'env.lib.python3.5.site-packages.django.contrib.flatpages',
              'env.lib.python3.5.site-packages.django.contrib.flatpages.migrations',
              'env.lib.python3.5.site-packages.django.contrib.flatpages.templatetags',
              'env.lib.python3.5.site-packages.django.contrib.redirects',
              'env.lib.python3.5.site-packages.django.contrib.redirects.migrations',
              'env.lib.python3.5.site-packages.django.contrib.staticfiles',
              'env.lib.python3.5.site-packages.django.contrib.staticfiles.management',
              'env.lib.python3.5.site-packages.django.contrib.staticfiles.management.commands',
              'env.lib.python3.5.site-packages.django.contrib.staticfiles.templatetags',
              'env.lib.python3.5.site-packages.django.contrib.syndication',
              'env.lib.python3.5.site-packages.django.contrib.contenttypes',
              'env.lib.python3.5.site-packages.django.contrib.contenttypes.management',
              'env.lib.python3.5.site-packages.django.contrib.contenttypes.management.commands',
              'env.lib.python3.5.site-packages.django.contrib.contenttypes.migrations',
              'env.lib.python3.5.site-packages.django.dispatch', 'env.lib.python3.5.site-packages.django.template',
              'env.lib.python3.5.site-packages.django.template.loaders',
              'env.lib.python3.5.site-packages.django.template.backends',
              'env.lib.python3.5.site-packages.django.middleware',
              'env.lib.python3.5.site-packages.django.templatetags', 'env.lib.python3.5.site-packages.setuptools',
              'env.lib.python3.5.site-packages.setuptools.extern', 'env.lib.python3.5.site-packages.setuptools._vendor',
              'env.lib.python3.5.site-packages.setuptools._vendor.packaging',
              'env.lib.python3.5.site-packages.setuptools.command', 'env.lib.python3.5.site-packages.pkg_resources',
              'env.lib.python3.5.site-packages.pkg_resources.extern',
              'env.lib.python3.5.site-packages.pkg_resources._vendor',
              'env.lib.python3.5.site-packages.pkg_resources._vendor.packaging', 'PCK_SBD', 'account', 'account.views',
              'account.migrations', 'care_point', 'care_point.view', 'care_point.migrations',
              'care_point.templatetags'],
    url='',
    license='owner',
    author='mario',
    author_email='perkowski.mar@gmial.com',
    description=''
)
