# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(b'umowa', b'umowa'), (b'zlecenie', b'zlecenie')], default=b'umowa', max_length=20)),
                ('date_from', models.DateField(blank=True, default=b'2018-11-07', null=True)),
                ('date_to', models.DateField(blank=True, default=b'2018-11-07', null=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Caregiver')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_payment', models.CharField(max_length=5)),
                ('hours', models.CharField(max_length=4)),
                ('charge', models.CharField(max_length=30)),
                ('activity', models.ManyToManyField(blank=True, to='care_point.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Point_of_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(b'umowa', b'umowa'), (b'zlecenie', b'zlecenie')], default=b'umowa', max_length=15)),
                ('date', models.DateField(blank=True, default=b'2018-11-07', null=True)),
                ('hour_from', models.TimeField(default=b'8:00')),
                ('hour_to', models.TimeField(default=b'10:00')),
                ('description', models.CharField(max_length=200)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Caregiver')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='point_of_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Point_of_care'),
        ),
        migrations.AddField(
            model_name='decision',
            name='illness',
            field=models.ManyToManyField(blank=True, to='care_point.Illness'),
        ),
        migrations.AddField(
            model_name='decision',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='point_of_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Point_of_care'),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
    ]
