# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('umowa', 'umowa'), ('zlecenie', 'zlecenie')], default='umowa', max_length=20)),
                ('date_from', models.DateField(blank=True, default='2018-12-11', null=True)),
                ('date_to', models.DateField(blank=True, default='2018-12-11', null=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Caregiver')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_payment', models.CharField(max_length=5)),
                ('hours', models.CharField(max_length=4)),
                ('charge', models.CharField(max_length=30)),
                ('activity', models.ManyToManyField(blank=True, to='care_point.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point_of_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WardActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Activity')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='WardIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision')),
                ('illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Illness')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('umowa', 'umowa'), ('zlecenie', 'zlecenie')], default='umowa', max_length=15)),
                ('date', models.DateField(blank=True, default='2018-12-11', null=True)),
                ('hour_from', models.TimeField(default='8:00')),
                ('hour_to', models.TimeField(default='10:00')),
                ('description', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Address')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Caregiver')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='point_of_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Point_of_care'),
        ),
        migrations.AddField(
            model_name='decision',
            name='illness',
            field=models.ManyToManyField(blank=True, to='care_point.Illness'),
        ),
        migrations.AddField(
            model_name='decision',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='point_of_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Point_of_care'),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
    ]
