# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 19:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(blank=True, default='2018-12-21', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(blank=True, default='2018-12-21', null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=30, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='decision',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=4, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='decision',
            name='percent_payment',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=5, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date',
            field=models.DateField(blank=True, default='2018-12-21', null=True),
        ),
    ]
