# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(blank=True, default='2018-11-07', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(blank=True, default='2018-11-07', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='genre',
            field=models.CharField(choices=[('umowa', 'umowa'), ('zlecenie', 'zlecenie')], default='umowa', max_length=20),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date',
            field=models.DateField(blank=True, default='2018-11-07', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='genre',
            field=models.CharField(choices=[('umowa', 'umowa'), ('zlecenie', 'zlecenie')], default='umowa', max_length=15),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hour_from',
            field=models.TimeField(default='8:00'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hour_to',
            field=models.TimeField(default='10:00'),
        ),
    ]
