# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0002_auto_20181107_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
        migrations.AddField(
            model_name='illness',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(blank=True, default='2018-11-11', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(blank=True, default='2018-11-11', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date',
            field=models.DateField(blank=True, default='2018-11-11', null=True),
        ),
    ]
