# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0003_auto_20181111_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WardIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='illness',
            name='ward',
        ),
        migrations.AddField(
            model_name='wardillness',
            name='illness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Illness'),
        ),
        migrations.AddField(
            model_name='wardillness',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
        migrations.AddField(
            model_name='wardactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Activity'),
        ),
        migrations.AddField(
            model_name='wardactivity',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
    ]
