# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0004_auto_20181111_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardactivity',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision'),
        ),
        migrations.AddField(
            model_name='wardillness',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision'),
        ),
    ]
