# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0004_auto_20181221_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='charge',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Podaj poprawną wartość', 'required': 'To pole jest wymagane'}, max_digits=6, max_length=30),
        ),
        migrations.AlterField(
            model_name='decision',
            name='hours',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Podaj poprawną wartość', 'required': 'To pole jest wymagane'}, max_digits=6, max_length=4),
        ),
        migrations.AlterField(
            model_name='decision',
            name='percent_payment',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Podaj poprawną wartość', 'required': 'To pole jest wymagane'}, max_digits=6, max_length=5),
        ),
    ]
