# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0005_auto_20181111_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='care_point.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(blank=True, default='2018-11-12', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(blank=True, default='2018-11-12', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date',
            field=models.DateField(blank=True, default='2018-11-12', null=True),
        ),
    ]
