# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0007_auto_20181221_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='activity',
            field=models.ManyToManyField(blank=True, to='care_point.Activity'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='illness',
            field=models.ManyToManyField(blank=True, to='care_point.Illness'),
        ),
    ]
