# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0008_auto_20181221_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=6),
        ),
        migrations.AlterField(
            model_name='decision',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=6),
        ),
        migrations.AlterField(
            model_name='decision',
            name='percent_payment',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=6),
        ),
    ]
